const opportunities = [
  {
    ref: "SEA-001",
    title: "English Conversation Club",
    category: "Education",
    location: "Bangkok, Thailand",
    commitment: "3 months",
    summary: "Host weekly conversation circles with university students and build friendships through practical English practice.",
    details: "This sample role helps students practice conversational English in a relaxed setting. Volunteers would prepare simple discussion prompts, listen well, and support local partners who are building long-term relationships.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Old_Quarter_street_scene%2C_Hanoi_%284%29_%2837610074295%29.jpg/640px-Old_Quarter_street_scene%2C_Hanoi_%284%29_%2837610074295%29.jpg",
    alt: "Busy street scene in Southeast Asia",
    search: "thailand english club university students education bangkok"
  },
  {
    ref: "SEA-002",
    title: "Village Water Project Support",
    category: "Community",
    location: "Kampong Thom, Cambodia",
    commitment: "2 weeks",
    summary: "Assist local partners with family visits, basic project logistics, and community follow-up in rural villages.",
    details: "This draft opportunity focuses on practical support for a community development partner. A volunteer might help document needs, organize supplies, and encourage families connected to clean water projects.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Cambo_167.jpg/640px-Cambo_167.jpg",
    alt: "Rural wooden home in Cambodia",
    search: "cambodia rural village water community families"
  },
  {
    ref: "SEA-003",
    title: "Island Health Outreach",
    category: "Medical",
    location: "Visayas, Philippines",
    commitment: "10 days",
    summary: "Serve alongside a mobile clinic team offering basic health checks, patient intake, and prayerful care.",
    details: "Medical and non-medical helpers could support patient flow, registration, basic hospitality, and follow-up conversations while local clinicians lead care.",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Mount_Phou_Si_from_the_Mekong.jpg",
    alt: "River and hill landscape in Laos",
    search: "philippines medical clinic nursing health outreach island visayas"
  },
  {
    ref: "SEA-004",
    title: "Mission Storytelling Team",
    category: "Media",
    location: "Jakarta, Indonesia",
    commitment: "1 month",
    summary: "Capture photos, interviews, and short updates that help supporters understand what God is doing locally.",
    details: "This role is for people who can write, photograph, edit video, or organize stories. The goal is to help supporters pray and participate with more clarity.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Batavia_City_Hall_%28Jakarta_History_Museum%29_Fatahillah_Square_%282025%29_-_img_03.jpg/640px-Batavia_City_Hall_%28Jakarta_History_Museum%29_Fatahillah_Square_%282025%29_-_img_03.jpg",
    alt: "Historic public square in Jakarta, Indonesia",
    search: "indonesia stories photography video media missions jakarta"
  },
  {
    ref: "SEA-005",
    title: "Youth Tutoring Program",
    category: "Education",
    location: "Hanoi, Vietnam",
    commitment: "6 weeks",
    summary: "Help teenagers with English, homework, and mentoring through an after-school program run by local believers.",
    details: "Tutors would prepare simple lessons, assist with homework, and build steady mentoring relationships in a supervised after-school environment.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Old_Quarter_street_scene%2C_Hanoi_%284%29_%2837610074295%29.jpg/640px-Old_Quarter_street_scene%2C_Hanoi_%284%29_%2837610074295%29.jpg",
    alt: "Street scene in Hanoi, Vietnam",
    search: "vietnam youth tutoring education school english hanoi"
  },
  {
    ref: "SEA-006",
    title: "Border Relief Care",
    category: "Community",
    location: "Thai-Myanmar Border",
    commitment: "2-4 weeks",
    summary: "Support trusted partners serving displaced families through supply sorting, listening visits, and children's activities.",
    details: "This sample placement is about steady, practical service with experienced relief partners. Tasks may include preparing supplies, helping with child-safe activities, and encouraging field teams.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Cambo_167.jpg/640px-Cambo_167.jpg",
    alt: "Rural home in Southeast Asia",
    search: "myanmar refugee families community relief border thailand"
  },
  {
    ref: "SEA-007",
    title: "Prayer Walking Team",
    category: "Prayer",
    location: "Luang Prabang, Laos",
    commitment: "1 week",
    summary: "Join a small team praying through neighborhoods and learning about unreached communities with local guides.",
    details: "Participants would pray onsite, listen to local guides, learn cultural context, and bring back focused prayer needs for supporters.",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Mount_Phou_Si_from_the_Mekong.jpg",
    alt: "View over Luang Prabang, Laos",
    search: "laos prayer walking unreached people groups intercession"
  },
  {
    ref: "SEA-008",
    title: "Migrant Worker Hospitality",
    category: "Community",
    location: "Kuala Lumpur, Malaysia",
    commitment: "Monthly",
    summary: "Help host shared meals, language practice, and practical care for migrant workers far from home.",
    details: "This opportunity centers on welcome and friendship. Volunteers may help prepare meals, lead conversation practice, and connect people with local support.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Cambo_167.jpg/640px-Cambo_167.jpg",
    alt: "Rural community home in Southeast Asia",
    search: "malaysia migrant workers hospitality community kuala lumpur"
  },
  {
    ref: "SEA-009",
    title: "Dental Clinic Assistant",
    category: "Medical",
    location: "Dili, Timor-Leste",
    commitment: "8 days",
    summary: "Assist a short-term dental team with registration, translation support, supplies, and patient care flow.",
    details: "Volunteers would support a visiting dental team under local guidance. Non-clinical roles include greeting patients, organizing supplies, and helping families move through appointments.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Batavia_City_Hall_%28Jakarta_History_Museum%29_Fatahillah_Square_%282025%29_-_img_03.jpg/640px-Batavia_City_Hall_%28Jakarta_History_Museum%29_Fatahillah_Square_%282025%29_-_img_03.jpg",
    alt: "Historic public building in Southeast Asia",
    search: "timor leste dental clinic health medical dili"
  },
  {
    ref: "SEA-010",
    title: "Digital Discipleship Content",
    category: "Media",
    location: "Singapore",
    commitment: "Remote friendly",
    summary: "Create simple posts, short videos, and training materials for online follow-up with seekers and new believers.",
    details: "This role can be done remotely or in person. Volunteers create clear, reusable digital content that helps local teams follow up with people exploring faith.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Batavia_City_Hall_%28Jakarta_History_Museum%29_Fatahillah_Square_%282025%29_-_img_03.jpg/640px-Batavia_City_Hall_%28Jakarta_History_Museum%29_Fatahillah_Square_%282025%29_-_img_03.jpg",
    alt: "Urban public square in Southeast Asia",
    search: "singapore digital discipleship media social content training"
  },
  {
    ref: "SEA-011",
    title: "Culture and Language Helper",
    category: "Education",
    location: "Bandar Seri Begawan, Brunei",
    commitment: "Flexible",
    summary: "Encourage cross-cultural workers through language practice, cultural research, and simple learning resources.",
    details: "This flexible support role helps field workers continue learning well. A volunteer could organize vocabulary lists, practice conversations, or research cultural questions.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Old_Quarter_street_scene%2C_Hanoi_%284%29_%2837610074295%29.jpg/640px-Old_Quarter_street_scene%2C_Hanoi_%284%29_%2837610074295%29.jpg",
    alt: "Street scene in Southeast Asia",
    search: "brunei language learning culture education tutoring"
  },
  {
    ref: "SEA-012",
    title: "Regional Prayer Coordinator",
    category: "Prayer",
    location: "Regional",
    commitment: "Remote",
    summary: "Gather prayer requests from field teams and help supporters pray regularly for Southeast Asia missions.",
    details: "This remote role turns field updates into clear prayer prompts. It could include monthly email updates, country prayer sheets, and care notes for teams.",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Mount_Phou_Si_from_the_Mekong.jpg",
    alt: "Landscape view in Laos",
    search: "southeast asia prayer coordinator missions intercession regional"
  }
];
